### ISSUE TITLE
Add ergonomic location dependency

### ISSUE THREAD

**Issue by RemiBardon** [tgrapperon/swift-dependencies-additions#71]
After we add support for `CLLocationManager`, I would like to add a more ergonomic wrapper around it, allowing things like `getLocation() async throws -> CLLocationCoordinate2D`.

With `CLLocationManager` working with a delegate pattern, it's a bit complex to implement correctly but I did it in a simple project so I should be able to replicate it here.

I'm just not sure what features we would like to add in this dependency. Thinking about it for 1 minute, I see something like:

- `getLocation() async throws -> CLLocationCoordinate2D`
- `locations() -> AsyncStream<CLLocationCoordinate2D>`

**Comment by tgrapperon** [comment]
I'm closing it as the location manager issue has moved to a discussion (#72), but feel free to repost in there to open the discussion!
